# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x03tts\",\n\nTTSRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"\x1c\n\x0bTTSResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\")\n\x11TTSBase64Response\x12\x14\n\x0c\x61udio_base64\x18\x01 \x01(\t2\x82\x01\n\nTTSService\x12\x33\n\x0eGenerateSpeech\x12\x0f.tts.TTSRequest\x1a\x10.tts.TTSResponse\x12?\n\x14GenerateSpeechBase64\x12\x0f.tts.TTSRequest\x1a\x16.tts.TTSBase64Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TTSREQUEST']._serialized_start=18
  _globals['_TTSREQUEST']._serialized_end=62
  _globals['_TTSRESPONSE']._serialized_start=64
  _globals['_TTSRESPONSE']._serialized_end=92
  _globals['_TTSBASE64RESPONSE']._serialized_start=94
  _globals['_TTSBASE64RESPONSE']._serialized_end=135
  _globals['_TTSSERVICE']._serialized_start=138
  _globals['_TTSSERVICE']._serialized_end=268
# @@protoc_insertion_point(module_scope)
